### ISSUE TITLE
let me show you my pokemans

### ISSUE THREAD

**Issue by jbenet** [ipfs/go-ipfs#2715]
```sh
mkdir foo
echo "bar" >foo/bar
f=$(ipfs add -r -q foo | tail -n1)
r=$(ipfs object new unixfs-dir);
r=$(ipfs object patch $r add-link bar /ipfs/$f/bar)
ipfs cat /ipfs/$r/bar
cat wat.png
```

![](http://meowcheese.com/sites/meowcheese.com/files/images/2008/04/let-me-show-you-my-pokemans.jpg)

#### TODO

- [x] check nil key in blockstore.Get and add test
- [x] check nil key in dagservice.Get and add test
- [x] object patch add-link should ParsePath and core.Resolve (not just parse key)
- [ ] rm-link and other patch cmds same thing

**Comment by whyrusleeping** [comment]
Nit: theres not a pokemon game cartridge in that GBA.
