### ISSUE TITLE
Code Review v0.4.4...v0.4.5

### ISSUE THREAD

**Issue by lgierth** [ipfs/go-ipfs#3534]
Reflects ipfs/go-ipfs@c99a82d4b53347b32b8d1b0a0df0250e36a13c8d

Notable changes
- IPLD and CIDs
  - [ ] Rework go-ipfs to use content IDs version 0                -- ipfs/go-ipfs#3187
  - [ ] The conquest of El Cid, Pt. 2                -- ipfs/go-ipfs#3290
  - [ ] Turn merkledag.Node into an interface                              -- ipfs/go-ipfs#3301
  - [ ] Implement cbor ipld nodes and a first pass at the 'dag' command                -- ipfs/go-ipfs#3325
  - [ ] allow cid format selection in block put command                -- ipfs/go-ipfs#3324
  - [ ] cmd/block: add selection of multihash parameters to block put command                -- ipfs/go-ipfs#3483
  - [ ] bitswap: protocol extension to handle cids                -- ipfs/go-ipfs#3297
  - [ ] Add dag and stat to command help info                -- ipfs/go-ipfs#3422
  - [ ] dag get should be a read only command                -- ipfs/go-ipfs#3499
  - [ ] dag/get: accept paths and not just cids                -- ipfs/go-ipfs#3517
  - [ ] ds-help: add helper functions to convert from Cid to DsKey and the reverse                -- ipfs/go-ipfs#3310
  - [ ] Issue #3419: Do not recursively resolve DAG just to obtain a CID                -- ipfs/go-ipfs#3420
  - [ ] merkledag: retain cid types when roundtripping through a ProtoNode                -- ipfs/go-ipfs#3443
  - [ ] Fix "ipfs ls" so it works correctly with raw leaves. -- ipfs/go-ipfs#3557
- Raw Nodes
  - [ ] Implement 'Raw Node' node type                -- ipfs/go-ipfs#3307
  - [ ] merkledag: optimize DagService GetLinks for Raw Nodes.                -- ipfs/go-ipfs#3351
  - [ ] Fix panic in dagreader with raw nodes                -- ipfs/go-ipfs#3403
- Experimental PubSub
  - [ ] Add a very basic many to many pubsub                -- ipfs/go-ipfs#3202
  - [ ] Send empty struct to pubsub cmd output to flush                -- ipfs/go-ipfs#3416
  - [ ] cmd/pubsub: fix peers command topic filtering                -- ipfs/go-ipfs#3484
  - [ ] add sharness test for pubsub                          -- ipfs/go-ipfs#3432
- Core API
  - [ ] gateway: use core api for serving GET/HEAD/POST                -- ipfs/go-ipfs#3244

changes
- [ ] gateway: disable Suborigins as it conflicts the spec                -- ipfs/go-ipfs#3519
- [ ] blockstore: rename RuntimeHashing to HashOnRead                -- ipfs/go-ipfs#3143
- [ ] ipfs/cat: disable auto-gc check                -- ipfs/go-ipfs#3100
- [ ] Revert Add Defaults to `ipfs add` / Fix default logic of `--progress` option                -- ipfs/go-ipfs#3464

improvements
- [ ] bitswap: add `ledger` subcommand                -- ipfs/go-ipfs#2852
- [ ] Add "ipfs block rm" command.                -- ipfs/go-ipfs#2962
- [ ] add config option to disable bandwidth metrics                -- ipfs/go-ipfs#3381
- [ ] add experimental dht client mode flag                -- ipfs/go-ipfs#3269
- [ ] reprovider: add config option to set reprovide interval                -- ipfs/go-ipfs#3101
- [ ] cmds: implement ipfs dht provide command                -- ipfs/go-ipfs#3106
- [ ] allow listing of streams to connected peers                -- ipfs/go-ipfs#3352
- [ ] add option to enable go-multiplex experiment                -- ipfs/go-ipfs#3447
- [ ] basic keystore implementation                -- ipfs/go-ipfs#3472
- [ ] ipfs/add: make --local flag not write out providers                -- ipfs/go-ipfs#3102
- [ ] dont buffer entire input for tar adds                               -- ipfs/go-ipfs#3334
- [ ] gateway: degrade error in gateway to log to reduce noise                -- ipfs/go-ipfs#2971
- [ ] datastore: blockstore should retry when it encounters temp errors                -- ipfs/go-ipfs#3091
- [ ] Adder: Don't hold the PinLock when not pinning.                -- ipfs/go-ipfs#3222
- [ ] cmd: validate repo/api file and print nicer error message                -- ipfs/go-ipfs#3219
- [ ] no longer hard code gomaxprocs                               -- ipfs/go-ipfs#3357
- [ ] bash_completion: Add a couple missing commands                -- ipfs/go-ipfs#3369
- [ ] Updated Bash complete script                                           -- ipfs/go-ipfs#3377
- [ ] blockstore: fix TODO and avoid calling ds.NewKey                -- ipfs/go-ipfs#3379
- [ ] blockstore: remove expensive debug statement in AllKeysChan                -- ipfs/go-ipfs#3384
- [ ] Remove GC timeout, fix GC tests                               -- ipfs/go-ipfs#3494
- [ ] merkledag: add a concurrency limit to merkledag fetch graph                -- ipfs/go-ipfs#3495
- [ ] "block rm": make channel large enough to avoid blocking                -- ipfs/go-ipfs#3418
- [ ] namesys: add entry to DHT cache after publish                -- ipfs/go-ipfs#3501
- [ ] namesys: fix case where there is no cache                -- ipfs/go-ipfs#3509
- [ ] add in option to use nil-routing -- ipfs/go-ipfs#3605
- [ ] "ipfs key list": include the hash of the key id in addition to the name -- ipfs/go-ipfs#3581

bitswap
- [ ] bitswap: don't re-provide blocks we've provided very recently                -- ipfs/go-ipfs#3105
- [ ] bitswap: add a deadline to sendmsg calls                     -- ipfs/go-ipfs#3445
- [ ] cleanup bitswap and handle message send failure slightly better                -- ipfs/go-ipfs#3408
- [ ] bitswap: increase wantlist resend delay to one minute                -- ipfs/go-ipfs#3448
- [ ] bitswap: add wantlist fullness to protobuf messages                -- ipfs/go-ipfs#3461
- [ ] update message.proto with comments                                       -- ipfs/go-ipfs#3476
- [ ] only pass keys down newBlocks chan in bitswap                          -- ipfs/go-ipfs#3271
- [ ] Fix minor typo in bitswap debug logging                            -- ipfs/go-ipfs#3178

fixes
- [ ] gateway: fix --writable flag :|                               -- ipfs/go-ipfs#3206
- [ ] unixfs: fix relative seek not expanding file properly                 -- ipfs/go-ipfs#3095
- [ ] use correct protocol names for ipfs services                -- ipfs/go-ipfs#3132
- [ ] dht: add missing protocol ID to newStream call                -- ipfs/go-ipfs#3203
- [ ] namesys: return right after errors                               -- ipfs/go-ipfs#3345
- [ ] fuse: make osxfuse check config check more permissive                -- ipfs/go-ipfs#3098
- [ ] fuse: Parse OSX fuse version properly                               -- ipfs/go-ipfs#3413
- [ ] Fixes nc on macOS not closing socket when the stdin sends EOF                -- ipfs/go-ipfs#3515
- [ ] commands: fix opt.Description panic when desc was empty                -- ipfs/go-ipfs#3521
- [ ] Fixes #3133: Properly handle release candidates in version comparison                -- ipfs/go-ipfs#3136
- [ ] "block rm": move core functionally into blockstore_util package                -- ipfs/go-ipfs#3225
- [ ] Don't drop error in readStreamedJson.                               -- ipfs/go-ipfs#3276
- [ ] cmd/ipfs: error out on invalid routing option                -- ipfs/go-ipfs#3482
- [ ] respect contexts when returning diagnostics responses                -- ipfs/go-ipfs#3353
- [ ] fix formatting on error call                                       -- ipfs/go-ipfs#3435
- [ ] merkledag: fix json marshalling of pbnode                -- ipfs/go-ipfs#3507
- [ ] rewrite enumerate children async to be less fragile -- ipfs/go-ipfs#3571
- [ ] Fix weird trailing message in default os check. -- ipfs/go-ipfs#3591

general changes and refactorings
- [ ] pin: use separate dagservice for storing pinsets                -- ipfs/go-ipfs#3103
- [ ] cli: refactor to expose argument parsing functionality                -- ipfs/go-ipfs#3308
- [ ] Revert "http api: makes sure header is sent even when r is not ready …                -- ipfs/go-ipfs#3366
- [ ] Create a FilestoreNode object to carry PosInfo                -- ipfs/go-ipfs#3314
- [ ] swarm/peers: print 'n/a' instead of zero latency                -- ipfs/go-ipfs#3491
- [ ] blockstore: fix PutMany with cache logic                            -- ipfs/go-ipfs#3162
- [ ] Add DAGService.GetLinks() method and use it in the GC and elsewhere.                -- ipfs/go-ipfs#3255
- [ ] Create a write-through block service                            -- ipfs/go-ipfs#3294
- [ ] make path resolver no longer require whole node for construction                -- ipfs/go-ipfs#3321
- [ ] Distinguish between Offline and Local Mode.                            -- ipfs/go-ipfs#3259
- [ ] Separate out the G.C. Locking from the Blockstore interface.                -- ipfs/go-ipfs#3348
- [ ] ds-help: avoid unnecessary allocs when posssible and make use of RawKey                -- ipfs/go-ipfs#3407
- [ ] Use NextSync method in Datastore                                       -- ipfs/go-ipfs#3386
- [ ] Switch unixfs.Metadata.MimeType to optional                     -- ipfs/go-ipfs#3458
- [ ] blockservice: avoid using unnecessary continue statement -- ipfs/go-ipfs#3590
- [ ] "ipfs name publish": use path.ParsePath instead of casting input -- ipfs/go-ipfs#3592
- [ ] Fix inconsistent `ipfs stats bw` formatting -- ipfs/go-ipfs#3554
- [ ] Clean up minor issues in 0.4.5 cr. -- ipfs/go-ipfs#3562
- [ ] set the agent version based on version string -- ipfs/go-ipfs#3569
- [ ] make: unsilence gx -- ipfs/go-ipfs#3586

bsd
- [ ] dist_get: Explicitly specify the input file to tar with "-f -"                -- ipfs/go-ipfs#3264
- [ ] ulimit: Tune resource limits on BSDs                                           -- ipfs/go-ipfs#3374
- [ ] ulimit: handle freebsd ulimit code separately from the rest of the un…                -- ipfs/go-ipfs#3450

metrics
- [ ] metrics: introduce go-metrics-interface                      -- ipfs/go-ipfs#3189
- [ ] Fix metrics injection                                           -- ipfs/go-ipfs#3315

misc
- [ ] Ipfs 0.4.5, pre-release 2 -- ipfs/go-ipfs#3623
- [ ] bump go requirement to 1.7                -- ipfs/go-ipfs#3111
- [ ] Merge 0.4.3 release candidate changes back into master                -- ipfs/go-ipfs#3248
- [ ] changelog: update for 0.4.3                -- ipfs/go-ipfs#3249
- [ ] changelog: fix 0.4.3-rc dates                -- ipfs/go-ipfs#3358
- [ ] changelog: add 0.4.4                -- ipfs/go-ipfs#3497
- [ ] bump dev version to 0.4.5                -- ipfs/go-ipfs#3298
- [ ] assets: add security@ipfs.io GPG key                -- ipfs/go-ipfs#2997
- [ ] Change LICENSE year                -- ipfs/go-ipfs#3145
- [ ] Updated authors doc                               -- ipfs/go-ipfs#2800
- [ ] pm: Reverse label numbers                -- ipfs/go-ipfs#3146
- [ ] Cleanup makefiles                -- ipfs/go-ipfs#2999
- [ ] use $(MAKE) instead of 'make' in Makefiles (follow-up to f3dc11c)                -- ipfs/go-ipfs#3265
- [ ] Refactoring install.sh                -- ipfs/go-ipfs#3194
- [ ] Add check if go code is formatted                -- ipfs/go-ipfs#3421
- [ ] gx: fix dvcsimport path in package.json                -- ipfs/go-ipfs#3217
- [ ] bin: dist_get script: prevents get_go_vars() returns same values twice                -- ipfs/go-ipfs#3079
- [ ] Resort imports in core/core.go                                       -- ipfs/go-ipfs#3395

deps
- [ ] Update libp2p to have fixed spdystream dep                -- ipfs/go-ipfs#3210
- [ ] update libp2p and dht packages                -- ipfs/go-ipfs#3263
- [ ] update to libp2p 4.0.1 and propogate other changes                -- ipfs/go-ipfs#3284
- [ ] update to libp2p 4.0.4                -- ipfs/go-ipfs#3361
- [ ] Update go-libp2p across codebase                -- ipfs/go-ipfs#3406
- [ ] update to go-libp2p 4.1.0                -- ipfs/go-ipfs#3373
- [ ] update deps for libp2p 3.4.0                -- ipfs/go-ipfs#3110
- [ ] update go-libp2p-swarm with deadlock fixes                -- ipfs/go-ipfs#3339
- [ ] update to new cid and ipld node packages                -- ipfs/go-ipfs#3326
- [ ] update to newer ipld node interface with Copy and better Tree                -- ipfs/go-ipfs#3391
- [ ] update experimental go-multiplex to 0.2.6                -- ipfs/go-ipfs#3475
- [ ] use floodsub version 0.8.1                -- ipfs/go-ipfs#3402
- [ ] bubble up go-datastore deps                -- ipfs/go-ipfs#3438
- [ ] Update go-ds-measure to 1.1.0                -- ipfs/go-ipfs#3502
- [ ] Update goprocess dependency to 1.0.0                -- ipfs/go-ipfs#3260
- [ ] routing: rework interfaces to make separation easier                -- ipfs/go-ipfs#3107
- [ ] routing: use extracted dht and routing code                -- ipfs/go-ipfs#3220
- [ ] dht: update to dht code with fixed GetClosestPeers                -- ipfs/go-ipfs#3346
- [ ] deps: move go-is-domain to gx                -- ipfs/go-ipfs#3077
- [ ] Extract blocks/key to ipfs/go-key                -- ipfs/go-ipfs#3198
- [ ] Extract thirdparty/loggables and thirdparty/peerset                -- ipfs/go-ipfs#3204
- [ ] completely remove go-key dep                -- ipfs/go-ipfs#3439
- [ ] remove randbo dep, its no longer needed                -- ipfs/go-ipfs#3118
- [ ] update to the correct ipld cbor code -- ipfs/go-ipfs#3616
- [ ] update dht code to drop error log to warning -- ipfs/go-ipfs#3611
- [ ] update go-libp2p with negotiate lazy fixes -- ipfs/go-ipfs#3582
- [ ] update libp2p for identify configuration updates -- ipfs/go-ipfs#3539
- [ ] Use newer flatfs sharding scheme -- ipfs/go-ipfs#3608

testing
- [ ] Improve test coverage all over the
- [ ] ipfs-test-lib: fix test_fsh arg quoting                -- ipfs/go-ipfs#3085
- [ ] test: 100% coverage for blocks/blocksutil                -- ipfs/go-ipfs#3090
- [ ] test: 100% coverage on blocks/set                -- ipfs/go-ipfs#3084
- [ ] test: 81% coverage on blockstore                -- ipfs/go-ipfs#3074
- [ ] test: reach 80% coverage of unixfs/mod                -- ipfs/go-ipfs#3096
- [ ] test: 82% coverage on blocks                         -- ipfs/go-ipfs#3086
- [ ] Test: unixfs @ 87% coverage                          -- ipfs/go-ipfs#3492
- [ ] Test/routing/offline                            -- ipfs/go-ipfs#3516
- [ ] Add test for flags package                          -- ipfs/go-ipfs#3449
- [ ] improve test coverage on merkledag package                -- ipfs/go-ipfs#3113
- [ ] test: 80% coverage of unixfs/io [WIP]                -- ipfs/go-ipfs#3097
- [ ] test: accept more than one digit in repo version tests                -- ipfs/go-ipfs#3130
- [ ] sharness: fix typo in hash in t0050                -- ipfs/go-ipfs#3170
- [ ] sharness: don't run go-ipfs instance with default config                -- ipfs/go-ipfs#3526
- [ ] trying to debug random test failures                -- ipfs/go-ipfs#3242
- [ ] add test to be run to detect future regressions in pinsets                -- ipfs/go-ipfs#3302
- [ ] Report coverage to coveralls                          -- ipfs/go-ipfs#3460
- [ ] Do not include core/commands in coverage report                -- ipfs/go-ipfs#3466
- [ ] Switch coverage to codecov from coveralls                -- ipfs/go-ipfs#3473
- [ ] Do not require CI to pass for coverage                -- ipfs/go-ipfs#3474
- [ ] Add multiple small tests                          -- ipfs/go-ipfs#3477
- [ ] Add test for 'ipfs config replace'                -- ipfs/go-ipfs#3073
- [ ] fix bug in pinsets and add a stress test for the scenario                -- ipfs/go-ipfs#3273
- [ ] Fix/random repo test failure -- ipfs/go-ipfs#3619
- [ ] test: add test for invalid routing option -- ipfs/go-ipfs#3584
- [ ] test: add test for dag service doing short circuit for raw.Links() -- ipfs/go-ipfs#3583

docs
- [ ] Update dns help with a correct domain name                -- ipfs/go-ipfs#3087
- [ ] Add period to `ipfs pin rm`                         -- ipfs/go-ipfs#3088
- [ ] Make all Taglines use imperative mood                -- ipfs/go-ipfs#3041
- [ ] Document listing commands better                -- ipfs/go-ipfs#3083
- [ ] readme: add notes on building for uncommon systems                -- ipfs/go-ipfs#3051
- [ ] docs: add branch naming conventions                -- ipfs/go-ipfs#3035
- [ ] commands: replace <default> keyword with <<default>>                -- ipfs/go-ipfs#3129
- [ ] Doc/cmds/log notice unused                            -- ipfs/go-ipfs#3160
- [ ] coreunix: fix Add() docs regarding pinning                -- ipfs/go-ipfs#3513
- [ ] README.md: Add sudo to install commands.                -- ipfs/go-ipfs#3201
- [ ] Edit issue reporting guides                          -- ipfs/go-ipfs#3006
- [ ] readme: add `-u` to gx install commands in manual build instructions                -- ipfs/go-ipfs#3236
- [ ] contribute.md: fix broken link to 'ammending commits' doc.                -- ipfs/go-ipfs#3281
- [ ] readme: fix go get invocations                        -- ipfs/go-ipfs#3288
- [ ] Added note about error codes                        -- ipfs/go-ipfs#2915
- [ ] docs: decapitalize IPFS where possible                -- ipfs/go-ipfs#2911
- [ ] Add docs for `"commands".Command.Run`                -- ipfs/go-ipfs#3382
- [ ] Fix help typo                                     -- ipfs/go-ipfs#3393
- [ ] Add default True to files flush                -- ipfs/go-ipfs#3167
- [ ] Put config keys in proper case                               -- ipfs/go-ipfs#3365
- [ ] add a note about ipfs key in the main helptext -- ipfs/go-ipfs#3580
- [ ] Fix link in `ipfs stats bw` help message -- ipfs/go-ipfs#3620

**Comment by whyrusleeping** [comment]
Some notes i took while going through and reviewing all this:

- unixfs/format_test.go, 7b16a8daa86e28c497f53a65f7d15ad778e8701d, TestMetedata name typo
- 58a2c5f8153c5061b3a9e2211cf85144e819c621, no test for invalid routing option error message
- 38703a8a7fb7e255ac58fe6de0b58b51ced78494, unnecessarily changed formatting in proto file
- 650eeee7cc04156d8251440d90d778f0a7b98d07, not sure we want to completely silence gx install output
- 805b504043ccf832056138cc32e38406e9a3d2e0, 'ipfs key list' should also list key hash ID (perhaps with an option)
- core/commands/publish.go, should use path.ParsePath instead of simply casting input to path.Path
- e76b14aef05acb8ca797946998f2f9366035d848, looks like @Kubuxu manually edited the package.json resulting in weird formatting (Was later fixed)
- 1b3158f8604276da5c03a754cac41ab60e713356, a few trailing spaces in t0180-pubsub.sh
- 8ee4280f7b52e70b7ee3d7944f77c3425507ab62, potentially unnecessary change in generated protobuf struct tags adding 'name=XYZ' fields
- ba383eda00b282545ad1da82473a096e3cd71fa3, trailing whitespace, @kevina do you have go-fmt on save setup?
- 1fd99dae50dff44d81d42582b49c9d5b5e3238c8, unixfs/io/pbdagreader.go, in default case of NewPBFileReader I would prefer to expand the error checking out
- 1e3b4aef665923bb93eb54fae6b28a34d17b8685, default os check case leaves a weird trailing message, also no tests for empty multiaddr (protocols == 0) thing
- 43320e1b7f91a3af799102dbb0f9bba8cd5de44c, would prefer the defer'ed dr.Close() happens after the switch, not a big deal though
- 396c629301c2c5cdf23f9d77ea9430e322f480a9, need more tests around Tree and Copy methods for protonode
- aae9eb789115c7101afcc87622e4d7740f0e9448, weird that merge commit has changes in it...
- c6186982e8ee74ceaa66d714e666584e4ef7eb67, would be nice to have a test that reproduces the issue this revert fixes (maybe using curl?)
- c31e4f7226467ed8e703bfbff553ef1c2f586018, not sure if we have tests for the context cancelling in the gateway. We should make sure to add these once this gets extracted
- 4a029c737415930cb0297f797ca97317cfd313de, need tests for swarm peers verbose mode
- bfe7ad7ec30ebf0e9914ed1cf58076ffca51d119, should probably add a test here that lists links of a raw object that we don't have
- 02aa6b4714a63e424212ce2e29d0f4db03fb3b33, should no longer need null import. This is a holdover from Godeps aggressively removing things
- b78b29c8a3447aa56c2fd596bda3bd546bb079bf, tests for routing resolver failure cases might be nice. Do we have a good mock routing system?
- 8ce9963289bcba3f596353f28a942814b5bfff65, did i purposely remove an apostrophe from a comment in a sharness test?
- 48f7e14277146341079d9cad0cbaea0ed977c604, should add a test for 'ipfs ls' on a dir with raw nodes in it
- 01aee44679dd8cacd0ca198206041e3c3d7c48af, in the future, do name changes in one commit, and restructuring in another
- 1173c003f5b4ce1e991e78d360635a135091c8e3, in AddBlocks, append to array 'if !has' to avoid using extra flow control structures
- Aside: we should think about separating 'providing' from 'giving a block to bitswap'. This will make it easier to address the providers problem moving forward
- f4d7369c4a0eda7adf6fa0277a48db057e6c8ca2, should have caught the 'not sending fullness in wantlists' bug here, need better CR
- Note: when parsing a CID fails, we should return a better error message than 'unrecognized multibase encoding' or whatever it is we're spewing now
- cb3bda78b3a4afb5cc5e7c2c70a651a113aaaae4, oh boy. This one got lots of review i remember. Still worth everyone taking another look at it
- bf8021302c1cbca2719763fabec41d1c0dc3461c, we still need to get around to refactoring the 'node state' things, offline, epehemeral, etc

**Comment by whyrusleeping** [comment]
Important to look at for @jbenet are the bitswap message sender change (to support cids, bitswap 1.1.0 and 1.0.0) and the merkledag dagservice changes to support cbor nodes, raw nodes, and the original protobufs

**Comment by kevina** [comment]
@whyrusleeping, if you want go through and create pull requests to fix most of these issues, let me know.

**Comment by kevina** [comment]
> 8ce9963, did i purposely remove an apostrophe from a comment in a sharness test?

yes, and I even mentioned it to you, something about about it causing problems with your editor :)

**Comment by whyrusleeping** [comment]
I'm a dolt

**Comment by kevina** [comment]
> I'm a dolt

Do you want me to fix it?

**Comment by whyrusleeping** [comment]
That might be a very difficult problem to fix, you can try.

**Comment by kevina** [comment]
@whyrusleeping, I meant add back the apostrophe. :)  I am fixing minor formatting/spelling issues now.

**Comment by kevina** [comment]
> 38703a8, unnecessarily changed formatting in proto file

don't see the problem other than diff noise, the changes help with consistency

> unixfs/format_test.go, 7b16a8d, TestMetedata name typo
> 1b3158f, a few trailing spaces in t0180-pubsub.sh
> 8ce9963, did i purposely remove an apostrophe from a comment in a sharness test?

fixed in pr #3562

> ba383ed, trailing whitespace, @kevina do you have go-fmt on save setup?

Already fixed, sorry.

> 8ee4280, potentially unnecessary change in generated protobuf struct tags adding 'name=XYZ' fields

this was talked about in the issue

**Comment by kevina** [comment]
I edited @whyrusleeping to be check boxes and checked resolved problems are ones where there is nothing to do.  Github has no editi history and also there is no notification sent when an edit is made so I will continue to add notes on items in separate comments.

**Comment by kevina** [comment]
> 48f7e14, should add a test for 'ipfs ls' on a dir with raw nodes in it

Now fixed.

> bfe7ad7, should probably add a test here that lists links of a raw object that we don't have

Your right. There is an issue for that.

**Comment by Kubuxu** [comment]
> bfe7ad7, should probably add a test here that lists links of a raw object that we don't have

Done in https://github.com/ipfs/go-ipfs/pull/3583

**Comment by Kubuxu** [comment]
> 43320e1, would prefer the defer'ed dr.Close() happens after the switch, not a big deal though

The close has to be where it is, due to one more error code that continues function flow but returns nil DagReader.

**Comment by kevina** [comment]
> 805b504, 'ipfs key list' should also list key hash ID (perhaps with an option)

#3581

**Comment by kevina** [comment]
> 1173c00, in AddBlocks, append to array 'if !has' to avoid using extra flow control structures

#3590

**Comment by kevina** [comment]
I have checked off all points that are either already addressed or are in an open p.r.  I will look into the following remaining issues:

> core/commands/publish.go, should use path.ParsePath instead of simply casting input to path.Path
> 1fd99da, unixfs/io/pbdagreader.go, in default case of NewPBFileReader I would prefer to expand the error checking out
> 1e3b4ae, default os check case leaves a weird trailing message, also no tests for empty multiaddr (protocols == 0) thing

What remains are some test, I might look into those after I address the above, but they are also testing parts of the code I am not familiar with so I am not sure how qualified I am to write them.

**Comment by kevina** [comment]
> core/commands/publish.go, should use path.ParsePath instead of simply casting input to path.Path

#3592

> 1fd99da, unixfs/io/pbdagreader.go, in default case of NewPBFileReader I would prefer to expand the error checking out

I am unsure what you are after here.

> 1e3b4ae, default os check case leaves a weird trailing message, also no tests for empty multiaddr (protocols == 0) thing

Fixed the first part in #3591.  Not 100% sure what you are after in the second part.

**Comment by lgierth** [comment]
I updated the list in the top comment -- 22 items added, for a total of now 199 changes. added:

misc
- [ ] Ipfs 0.4.5, pre-release 2 -- ipfs/go-ipfs#3623

deps
- [ ] update to the correct ipld cbor code -- ipfs/go-ipfs#3616
- [ ] update dht code to drop error log to warning -- ipfs/go-ipfs#3611
- [ ] update go-libp2p with negotiate lazy fixes -- ipfs/go-ipfs#3582
- [ ] update libp2p for identify configuration updates -- ipfs/go-ipfs#3539
- [ ] Use newer flatfs sharding scheme -- ipfs/go-ipfs#3608

ipld
- [ ] Fix "ipfs ls" so it works correctly with raw leaves. -- ipfs/go-ipfs#3557

docs
- [ ] add a note about ipfs key in the main helptext -- ipfs/go-ipfs#3580
- [ ] Fix link in `ipfs stats bw` help message -- ipfs/go-ipfs#3620

general
- [ ] blockservice: avoid using unnecessary continue statement -- ipfs/go-ipfs#3590
- [ ] "ipfs name publish": use path.ParsePath instead of casting input -- ipfs/go-ipfs#3592
- [ ] Fix inconsistent `ipfs stats bw` formatting -- ipfs/go-ipfs#3554
- [ ] Clean up minor issues in 0.4.5 cr. -- ipfs/go-ipfs#3562
- [ ] set the agent version based on version string -- ipfs/go-ipfs#3569
- [ ] make: unsilence gx -- ipfs/go-ipfs#3586

fixes
- [ ] rewrite enumerate children async to be less fragile -- ipfs/go-ipfs#3571
- [ ] Fix weird trailing message in default os check. -- ipfs/go-ipfs#3591

testing
- [ ] Fix/random repo test failure -- ipfs/go-ipfs#3619
- [ ] test: add test for invalid routing option -- ipfs/go-ipfs#3584
- [ ] test: add test for dag service doing short circuit for raw.Links() -- ipfs/go-ipfs#3583

features
- [ ] add in option to use nil-routing -- ipfs/go-ipfs#3605
- [ ] "ipfs key list": include the hash of the key id in addition to the name -- ipfs/go-ipfs#3581

**Comment by whyrusleeping** [comment]
closing this now
