### ISSUE TITLE
go-ipfs high priority issue list

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#4312]
This is a list of issues that we have identified as being critical to solve in the short term. Our goal is to have a majority of these resolved by the end of the year. Each issue is tagged with one or more owners, the owners arent necessarily the ones who need to fix the issue, they are just responsible for making sure it gets done.

- [x] [connection closing](https://github.com/libp2p/go-libp2p/issues/45) (whyrusleeping)
  - integrate connection closing
  - ipfs works fine with a restricted connection count
- [x] [websocket FD leaks](https://github.com/libp2p/go-ws-transport/issues/21) (stebalien)
  - don't leak file descriptors
- [ ] [DHT response handler performance](https://github.com/libp2p/go-libp2p-kad-dht/issues/88) (vyzo)
  - bootstrap node dht handler response time never over 1 second
- [x] [cbor performance](https://github.com/ipfs/go-ipld-cbor/issues/29) (whyrusleeping)
  - migrate to new, more performant and flexible cbor library (https://github.com/polydawn/refmt)
- [ ] [gc performance](https://github.com/ipfs/go-ipfs/pull/4149) (kubuxu, stebalien)
  - finish and merge @Kubuxus new GC PR
- [ ] [don't necessarily provide content when you add it](https://github.com/ipfs/go-ipfs/issues/4311) (magik6k)
  - provider strategies applied to initial adds
- [x] [bitswap session integrations for (cat, refs -r, get, ls)](https://github.com/ipfs/go-ipfs/issues/3786) (whyrusleeping)
- [ ] [flatfs successor recommended for use](https://github.com/ipfs/go-ipfs/issues/4279) (magic6k, whyrusleeping)
  - Badger 1.0 issue: https://github.com/dgraph-io/badger/issues/161
- [x] [no memory leaks](https://github.com/ipfs/go-ipfs/issues/3532) (whyrusleeping, stebalien)
- [x] [Swarm hotpaths optimized](https://github.com/libp2p/go-libp2p-swarm/issues/29) (stebalien)
- [x] [Profile all event handlers and fix slow ones](https://github.com/ipfs/go-ipfs/issues/4252) (stebalien)
- [x] [Pin with ton of hashes won't start](https://github.com/ipfs/go-ipfs/issues/4122) (stebalien)
- [x] [Avoid write corruption in go-multiplex](https://github.com/whyrusleeping/go-multiplex/issues/7) (stebalien)
- [x] [Fix floodsub go routine leak](https://github.com/libp2p/go-floodsub/issues/38) (stebalien)
- [x] [Better Buffering](https://github.com/ipfs/go-ipfs/issues/4280) (stebalien)
  - Comment: The motivating issue, metrics, was fixed. All of my attempts to add better buffering have lead to no improvement (so I haven't bothered getting them merged).
- [ ] [Duplicate Directory Entries](https://github.com/ipfs/go-ipfs/issues/4292)
- [ ] QmcTybF2LuVrm2W1sar1bqkaNjVmVrNdNpQdomz7sM8UTY (just a reminder for me)
- [x] [Share secio buffer pools between connections](https://github.com/ipfs/go-ipfs/issues/4397) (stebalien)

**Comment by myleshorton** [comment]
Just a quick 👍 to this list -- we'll likely have more details soon, but we've been re-integrating IPFS into Lantern @whyrusleeping , and definitely performance and CPU issues are the main blockers for up deploying it on a much wider scale.

**Comment by whyrusleeping** [comment]
@myleshorton thats great to hear! What version are you guys working with now? 0.4.12/13 should be much better off than any of the previous versions, and the next release is going to be a good deal better as well.  Please do let us know any issues you run into :)

**Comment by kvm2116** [comment]
Any estimate on when we expect Bitswap sessions to be implemented? 
How can I contribute to speed it along?

**Comment by whyrusleeping** [comment]
@kvm2116 the initial bitswap sessions code has been implemented, and is in use by `ipfs pin add`. It improves transfers pretty nicely, but doesnt currently do scheduling of asks between multiple peers.

The next thing we need to do is to add a coalescing layer around the DHT. We did a test run of making the http gateway use bitswap sessions, and it pegged the DHT with requests (sessions 'more correctly' does providers lookups). 

Last I checked, @magik6k had started working on that layer. I would ping him for a status update there.

**Comment by magik6k** [comment]
Part of this (https://github.com/ipfs/go-ipfs/pull/4333) is done and we wanted to merge it in 0.4.15,  I'll rebase it after 0.4.14 releases.

**Comment by DonaldTsang** [comment]
Post 20 month review: Updates on the checklist?

**Comment by Stebalien** [comment]
We finished most of them. This list was mostly a todo list for that quarter.

**Comment by Stebalien** [comment]
We finished most of them. This list was mostly a todo list for that quarter.
