### ISSUE TITLE
Migration towards base32 CIDv1

### ISSUE THREAD

**Issue by kevina** [ipfs/go-ipfs#5358]
*This issue is to form a migration plan to base32 CIDv1 specific to go-ipfs.  It is separate from #4143 which was more of a discussion or https://github.com/ipfs/ipfs/issues/337 which is more of a meta issue for all of go-ipfs, js-ipfs, and ipfs-companion.*

Phase 1:
   - [x]  Add ability to retrieve blocks even if given using a different CID version #5285
   - [ ] Add flag to `ipfs add` to return CIDs in alternative base 
   - [ ] Provide utility to convert between multibase encoding and CID versions #5229

Phase 2 -- full migration.
   - [ ] Refactor blockstore to work with bare multihashes instead of CIDs #5231
   - [ ] Figure out how to handle CID outputs in non-default multibase encoding #5349 (also #5234 and #5289).  This includes if the multibase should be preserved in CID and the addition of a global flag to specify the CID ibase.
   - [ ] Create config option for specifying full default cidv1 parameters #5230 
   - [ ] Figure out how to handle existing CidV0
     - [ ] How to handle the displaying of CIDv0 #5291
     - [ ] Normalize pins to CidV1?
     - [ ] Anything else?

cc @whyrusleeping @Stebalien @lidel @magik6k @kyledrake.

**Comment by kyledrake** [comment]
This is great, thank you for setting this up. LMK if you need anything from me.

**Comment by kevina** [comment]
Issues that I currently need feedback on from the core developers: 
  * Handling of Alternative Multibases #5349
  * How to handle CIDv0 as we migrate to CIDV1 #5291
  * Create config option for specifying full default cidv1 parameters #5230

**Comment by hsanjuan** [comment]
(subscribing)

**Comment by daviddias** [comment]
(subscribing)

**Comment by alanshaw** [comment]
Kind request 🙏 - there's a button on the right you can press to subscribe - commenting "(subscribing)" sends me and everyone else mentioned or participating a notification.

**Comment by lidel** [comment]
Some relevant updates from [Golang Core Dev Team Weekly Sync 2019-02-11](https://github.com/ipfs/team-mgmt/pull/871):

> #### Base32/CIDv1
> 
> [..]
> 
> @eingenito - Need to consider next steps and who/when this can be picked up. 
> @stebalien indicates that the next work to be done is converting the blockstore to use raw multihashes ([Issue](https://github.com/libp2p/go-libp2p-routing/issues/32), [WIP](https://github.com/ipfs/go-ipfs/pull/5510)). This is a complicated task that needs some context for whoever picks it up.
> 

Q: What's the relative priority of this task compared to others on [this list](https://github.com/ipfs/go-ipfs/issues/5358)? 	
A: Most important next milestone is storing/fetching [[raw] multihashes in the DHT in libp2p](https://github.com/libp2p/go-libp2p-routing/issues/32).

**Comment by DonaldTsang** [comment]
Idea: Use https://github.com/kstenerud/safe-encoding as a better alternative for safe encoding

**Comment by Stebalien** [comment]
On technical merits alone, those encoding schemes look superior (and the order-preserving property looks quite nice). Unfortunately, 

1. We're far enough into this switch that changing the default will require a pretty strong motivation.
2. The motivation for Base32 is wide (often built-in) language support.

**Comment by lidel** [comment]
Discussion that lead us to picking Base32 as the new default can be found in https://github.com/ipfs/go-ipfs/issues/4143#issuecomment-322630426:
> [..] chose RFC because it's a standard, it's been around a while, nginx-misc-module supports it, and it probably has the widest support across all programming languages. 

> The only reason I would chose the RFC one is because it is a standard and more likely to have an implementation available as part of the language.
 

@DonaldTsang encodings you linked look really interesting. 
I believe picking RFC one is still a good choice when it comes to being the new default, but we surely can add order-preserving ones as alternative encodings. Thank you for opening https://github.com/multiformats/multibase/issues/51, let's discuss them there.

**Comment by DaniellMesquita** [comment]
Important:

> what is the workaround to get the base32 hash of an file?

via: https://github.com/ipfs/go-ipfs/issues/7852

**Comment by lidel** [comment]
@DaniellMesquita you can convert any CID to CIDv1 in Base32 via:

```
ipfs cid base32 <cidv0>
```


You can also make a request to a subdomain gateway, eg. `https://dweb.link/ipfs/<cid>`, and you will be redirected to a subdomain with DNS-safe base32 or base36 CID:

https://dweb.link/ipfs/QmbWqxBEKC3P8tqsKc98xmWNzrzDtRLMiMPL8wBuTGsMnR → https://bafybeigdyrzt5sfp7udm7hu76uh7y26nf3efuylqabf3oclgtqy55fbzdi.ipfs.dweb.link/

**Comment by DaniellMesquita** [comment]
@lidel, ok, but how to get the base32/CIDv1 of an local file like in `ipfs add -q --only-hash`? Using pipelines with both commands?

**Comment by DaniellMesquita** [comment]
Ok, the pipelines command to get the CIDv1 of an file is: `ipfs add -q --only-hash <file.extension> | ipfs cid base32`

**Comment by hsanjuan** [comment]
`ipfs add --cid=version=1` should default to base32 output.

**Comment by DaniellMesquita** [comment]
@hsanjuan, this command isn't compatible with the purpose of only getting the CID of an given file, instead of adding it to IPFS.

lidel told me before that the flag to get CIDv1/base32 is `--cid-version 1` probably instead of the `--cid=version=1` you're mentioning.

Then, maybe `ipfs add -q --cid-version 1 --only-hash` is the command to just get the CIDv1 of an file.

> @lidel, So, its ipfs add -q --cid-version 1 --only-hash?
> 
> Is it bad to produce an different merkletree/DAG? Then, how to keep compatibility?

via: https://github.com/ipfs/go-ipfs/issues/7852#issuecomment-760468451

**Comment by lidel** [comment]
Triage: this tracking issue has served its purpose and can be closed. Here's the final status of every sub-item (mostly writing for myself, apologies for being terse/mental shortcuts):

  **Phase 1** -- all done years ago:

  - [x] Retrieve blocks using a different CID version (#5285) -- merged 2018-08-08
  - [ ] `ipfs add` flag for alternative base (#5233 / PR #5464) -- merged; global `--cid-base` flag now available on some commands via `core/commands/cmdenv/cidbase.go` but never properly wired everywhere due to lack of user need/interest -- fill issue if you need this, but... 
     - [x] ... Conversion utility (#5229 / PR #5385) -- merged; ships as `ipfs cid format`, `ipfs cid base32`, `ipfs cid bases`, `ipfs cid codecs`, `ipfs cid hashes`, usually solves user need when different CID representations are needed (user can self-service via one-line scripting in  bash etc)

  **Phase 2** -- all items resolved:

  - [x] **Refactor blockstore to bare multihashes (#5231)** -- closed 2021-09-29, continued as #6815. PR #6816 (commit `7f27dbfd1`, "feat: switch to raw multihashes for blocks") merged and shipped in **Kubo
  0.12.0** (Feb 2022). The blockstore now stores blocks keyed by multihash via `MultihashToDsKey()`. The old `thirdparty/cidv0v1/blockstore.go` CIDv0/v1 conversion wrapper was deleted in the same commit -- it's
  no longer needed since both CID versions resolve to the same multihash key. The external `blockstore.Blockstore` Go interface still accepts `cid.Cid` (not raw multihash) -- a library API cleanup tracked
  separately in [boxo#361](https://github.com/ipfs/boxo/issues/361), but this is cosmetic, not functional.
  - [ ] **Handle CID outputs in non-default multibase (#5349, #5234, #5289)** -- all closed. Global `--cid-base` and `--upgrade-cidv0-in-output` flags are present but NOT wired into every command that outputs CIDs. We never properly wired everywhere due to lack of user need/interest -- fill issue if you need this. 
  - [x] **Config option for default CIDv1 parameters (#5230)** -- closed 2026-02-04. PR #11148 landed the full [`Import.*`](https://github.com/ipfs/kubo/blob/master/docs/config.md#import) config section implementing [IPIP-499](https://github.com/ipfs/specs/pull/499): `Import.CidVersion`, `Import.HashFunction`, `Import.UnixFSRawLeaves`, `Import.UnixFSChunker`, plus DAG layout, link limits, HAMT settings, and more. Two predefined profiles make it a one-liner: `ipfs config profile apply unixfs-v1-2025` or `unixfs-v0-2015`.
  - [x] **Handle existing CIDv0 (#5291)** -- closed 2026-02-04. CIDv0 and CIDv1 coexist transparently: the multihash-based blockstore (#6816) serves the same block regardless of which CID version is used to request it, and the DHT provides/finds using raw multihashes.
  - [x] **Retrieve from legacy nodes using different CID version (#5378)** -- still technically open, but the concern is obsolete. See [#5378 comment](https://github.com/ipfs/kubo/issues/5378) for details. Since
   Kubo 0.12.0 (Feb 2022), both CID versions resolve to the same multihash-keyed block. Any node running 0.12+ handles cross-version retrieval transparently. The last pre-multihash release (0.11.x) is from late  2021, over 4 years ago.

  The original goal -- migrate to base32 CIDv1 -- is fully achievable today. Users can switch with one command and all the infrastructure (blockstore, routing, CLI, config) supports it.

The only remaining item is to eventually switch the implicit default to CIDv1 and modern profile, we will track that in:

- https://github.com/ipfs/kubo/issues/4143
