### ISSUE TITLE
Commands Library Upgrade

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-ipfs#5664]
Given the amount of interest in updating commands-lib commands to the latest commands-lib version (and the recently fixed bugs in MakeTypedEncoder), let's have a meta-issue.

General suggestions:

1. Prefer `MakeTypedEncoder`, it removes some boilerplate.
2. Old encoders tended to return `NewReader(someByteBufferOrString)`. In new code, prefer writing directly to the provided writer instead of first building up a temporary buffer/string.

Please *comment* below with the commands you're planning on fixing (just that).
They'll be checked off when actually fixed.

* [x] bitswap ledger #5676
* [x] bitswap reprovide #5676
* [x] bitswap wantlist #5676
* [x] bootstrap add #5678
* [x] bootstrap add default #5678
* [x] bootstrap list #5678
* [x] bootstrap rm #5678
* [x] bootstrap rm all #5678
* [x] config edit - #5659
* [x] config profile - #5659
* [x] config profile apply - #5659
* [x] config replace - #5659
* [x] config show - #5659
* [x] dag get - #5662
* [x] dag put - #5662
* [x] dag resolve - #5662
* [x] dht findpeer #5671
* [x] dht findprovs #5671
* [x] dht get #5671
* [x] dht provide #5671
* [x] dht put #5671
* [x] dht query #5671
* [x] diag cmds - #5659
* [x] diag cmds clear - #5659
* [x] diag cmds set-time - #5659
* [x] diag sys - #5659
* [x] dns - #5650
* [x] file ls #5756
* [x] files chcid #5665
* [x] files cp #5665
* [x] files flush #5665
* [x] files ls #5665
* [x] files mkdir #5665
* [x] files mv #5665
* [x] files read #5665
* [x] files rm #5665
* [x] filestore dups #5673
* [x] filestore verify #5673
* [x] log level - #5659
* [x] log ls - #5659
* [x] log tail - #5659
* [x] ls - #5611 #5663
* [x] mount - #5659
* [x] object data #5666
* [x] object diff #5666
* [x] object get #5666
* [x] object links #5666
* [x] object new #5666
* [x] object patch add-link #5666
* [x] object patch rm-link #5666
* [x] object patch set-data #5666
* [x] object put #5666
* [x] object stat #5666
* [x] p2p close #5672 
* [x] p2p forward #5672
* [x] p2p listen #5672
* [x] p2p ls #5672
* [x] p2p stream close #5672
* [x] p2p stream ls #5672
* [x] pin add
* [x] pin rm #5674
* [x] pin update #5674
* [x] pin verify #5674
* [x] ping #5664
* [x] refs #5679
* [x] refs local  #5679
* [x] repo fsck #5677
* [x] repo verify #5677
* [x] repo version #5677
* [x] tar add - #5650
* [x] tar cat - #5650
* [x] update #5730
* [x] version - #5650

**Comment by djdv** [comment]
Randomly going to grab the "object" section for now

**Comment by chenminjian** [comment]
I am planning to help with `ipfs repo`.

**Comment by kjzz** [comment]
I am doing with ping and object .Thx a lot.
@chenminjian @overbool

**Comment by kevina** [comment]
I can do the `filestore` commands and help review others.

**Comment by overbool** [comment]
@kevina There's already a pr about `filestore` (https://github.com/ipfs/go-ipfs/pull/5673/files)

**Comment by kevina** [comment]
@overbool oh okay, it would of been helpful if that was mentioned as a comment or pointed to in the initial description.

**Comment by overbool** [comment]
@Stebalien Maybe this issue can be closed.

**Comment by Stebalien** [comment]
Yep. Thanks for the reminder.
