### ISSUE TITLE
Release v0.4.20

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-ipfs#6163]
I promised a short release and got distracted. Luckily, @whyrusleeping came to the rescue so we're going to cut a release ASAP (RC1 on Wednesday).

The primary features will be:

1. Bitswap memory fixes.
2. Bitswap reduced provider workers.
3. Immediate providing of root blocks (with an on-disk provider queue).
4. Several panic fixes in the DHT.
5. Some NAT traversal improvements.
6. Reduced autonat delays. (probably needs a go mod update)
7. `ipfs add [--nocopy] URL`.
8. GO MODULES!

What am I missing?

TODOs:

* [x] Update to go 1.12 (https://github.com/ipfs/go-ipfs/pull/6144) tests are failing which is disturbing. (_@kubuxu is awesome_)
* [x] All the memory leaks!
  * [x] #6166 - relay and https://github.com/libp2p/go-ws-transport/pull/41
  * [x] #6168 - https://github.com/libp2p/go-libp2p-quic-transport/issues/53
* [ ] ~LevelDB panic #6146 (may be a memory corruption issue)~ no idea
* [x] Make sure to update go-libp2p for #6142.
* [x] Update badger (for new memory improvements) - https://github.com/ipfs/go-ds-badger/pull/57
* [x] Merge #6171 to tame the connection manager a bit.
* [x] Pull through the autorelay/autonat delay fixes if they're finished in time. - https://github.com/libp2p/go-libp2p-autonat/pull/20, https://github.com/libp2p/go-libp2p/pull/570

**Comment by reardenlife** [comment]
@Stebalien
> "What am I missing?"
Is there any way we can add a generation of PeerId through HTTP-RPC by supplying a public key?
I am struggling to obtain the feedback for the proposal: https://github.com/ipfs/go-ipfs/issues/6152

**Comment by CoreyLin** [comment]
@Stebalien Just want to confirm with you that v0.4.20 will be released today(3rd April), right? Thanks. I am waiting to use your latest release. 😃

**Comment by lordcirth** [comment]
@CoreyLin He said release candidate 1 on Wednesday.

**Comment by CoreyLin** [comment]
@lordcirth @Stebalien OK. So the release date is not finalized, right?

**Comment by olizilla** [comment]
Update to IPFS Web UI 2.4.4! I'll PR now.

**Comment by olizilla** [comment]
Done: https://github.com/ipfs/go-ipfs/pull/6169

**Comment by Stebalien** [comment]
@reardenlife I'm trying to avoid "one more thinging" this release.

@CoreyLin it'll be released when it's ready but I'm planning on cutting an RC1 today.

**Comment by raulk** [comment]
@stebalien at the risk of “one more thinging”(tm), exposing peer protection as a swarm command would be welcome by users and infra: https://github.com/libp2p/go-libp2p-connmgr/pull/36 it’s low risk as it doesn’t interfere with existing functionality nor the main loop

**Comment by Stebalien** [comment]
I'd like to avoid shipping a new command at this point. However, we can ship a custom build to infra.

**Comment by Stebalien** [comment]
OK, so the RC1's going to be coming tomorrow. I'd really like to get that QUIC fix in at least.

**Comment by vyzo** [comment]
Please also include an update of the `go-libp2p-autonat-svc` dependency (now at v0.0.4), as it cuts down the dialback timeout to 15s. The bootstrappers will also need to be updated for the new release.

**Comment by vyzo** [comment]
Note that I have tagged v0.0.4 in go-libp2p.

**Comment by Stebalien** [comment]
@vyzo done.

**Comment by Stebalien** [comment]
Status: wrestling with the distribution scripts and go modules (and trying not to break rebuilding of old versions with gx).

**Comment by lordcirth** [comment]
Are there any known issues with rc1 that need fixing?
