### ISSUE TITLE
IPNS over PubSub as an independent transport

### ISSUE THREAD

**Issue by aschmahmann** [ipfs/go-ipfs#6447]
IPNS over PubSub is not an independent transport from the standard IPNS over DHT. In particular, the first time a user tries to do an IPNS resolution when IPNS over PubSub is enabled it hits the DHT, and only on subsequent resolutions is PubSub utilized.

To accomplish this we need:
- [x] A mechanism to efficiently support persistence for PubSub
   - [x] ~~Use a persistent pubsub router by making gossipsub more configurable (libp2p/go-libp2p-pubsub#171).~~ Replaced with alternative proposals below. 
   - [x] Use validators + rebroadcasting in go-libp2p-pubsub-router to enable efficient persistence (libp2p/go-libp2p-pubsub-router#33)
   - [x] Have `Peer Join` events coming from PubSub (libp2p/go-libp2p-pubsub#190)
   - [x] Utilize the `Peer Join` events to ask for the latest state from peers so that we don't need to frequently rebroadcast (libp2p/go-libp2p-pubsub-router#33)
- [x] An easy to use mechanism for discovering peers in PubSub that is not tied to the DHT/content routing
  - e.g. As of [now](https://github.com/libp2p/go-libp2p-pubsub-router/blob/1b619f8d12950c3a6b91f93c08f29842af38a68c/pubsub.go#L331) IPNS uses go-libp2p-pubsub-router which uses content routing to bootstrap the DHT
  - [x] Utilize discovery interfaces in PubSub (https://github.com/libp2p/go-libp2p-pubsub/pull/184)
  - [ ] ~Have multiple discovery interfaces available for use (to prove out the interface)~
     - [ ] ~Rendezvous service (libp2p/go-libp2p-rendezvous#1)~
     - [x] Rendezvous discovery client (libp2p/go-libp2p-rendezvous#2)
- [x] Integrate improved IPNS over PubSub into go-ipfs
  - [ ] ~Change the applicable IPNS value routers to support querying both DHT and Rendezvous~
  - [ ] ~Add Rendezvous support into go-ipfs~
  - [x] Create a caching discovery mechanism that can use both DHT and Rendezvous servers and utilize that in pubsub-value-router (libp2p/go-libp2p-discovery#26)
  - [x] Bubble up all PubSub changes into go-ipfs (ipfs/go-ipfs#6758)

Some benefits of IPNS over PubSub as an independent transport from IPNS over DHT.
1) DHT performance issues are either less problematic or not relevant for us (depending on the discovery mechanism used)
2) We mostly get IPNS republishing for free (i.e. even if the publisher goes offline, other people can still make the IPNS record available). This means we can largely mitigate IPNS records that are abandoned by their authors since, as long as someone who cares about the record is maintaining and advertising it, the record will be available.
    - This is related to ipfs/go-ipfs#4435, since we would need a CLI method to indicate we want to `pin` an IPNS (public) key.

Demo and brief explanation of IPNS over PubSub as an independent transport (2m40s).
  - https://www.youtube.com/watch?v=XniIDIXU8RE

^ @autonome @lidel @Stebalien @momack2 

Update: Given that the rendezvous work has been put on hold by libp2p and that it's not actually necessary for PubSub to work as an independent transport those work items are now closed.

However, since we do already have MDNS discovery support (albeit not through the libp2p Discovery interfaces) IPNS over PubSub can function even in the total absence of a DHT.

**Comment by aschmahmann** [comment]
The only remaining issue is not with IPNS over PubSub as an independent transport, but with how we handle the multiple transports at an API level (https://github.com/ipfs/specs/issues/198#issuecomment-567663944).

This issue is closed for now and any PR fixing the above will link to this issue.
