### ISSUE TITLE
Testing Improvement Plan

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-ipfs#6483]
* CLI/API
  * Coverage
    * [ ] Merge #6075 (maybe with a few tweaks) and then fill out the flags that aren't covered.
  * Language Interop
    * [ ] Fix the current interop tests (https://github.com/ipfs/interop/issues/71).
    * [ ] Run sharness tests gainst both go-ipfs and js-ipfs (where possible).
  * Backwards Compatibility
    * [ ] Run sharness tests with previous go-ipfs binary as a client. Need to mark the required client version on sharness tests.
    * [x] Interop tests: These may be sufficient.
* Performance
  * [ ] End-to-end benchmarks (#6446) in CI.
* Reliability/Stability
  * [ ] Nightly _Mirror_ Gateway
    * [ ] Track and compare errors/latencies versus the gateway serving the response.
      * [ ] Auto-file Issues.
    * [ ] Auto deploy a nightly build.
    * [ ] Auto-file issues on crash. 
    * [ ] Automatically pull goroutine dumps, cpu profiles, and memory profiles.
    * [ ] Automatically analyze with [stackparse](https://github.com/ipfs/interop/issues/71) and auto-file issues when a specific goroutine count increases by 100x (usually indicates an issues). Note: this'll have a bunch of false positives but it's a good signal.
    * [ ] Same with the heap: File an issue if the "top memory user in a steady state" changes.
    * [ ] Same with the CPU profile.
  * [ ] Nightly Bootstrapper
    * [ ] Auto deploy a nightly build.
    * [ ] Auto-file issues on crash. 
    * [ ] Automatically pull goroutine dumps, cpu profiles, and memory profiles.
    * [ ] Automatically analyze with [stackparse](https://github.com/ipfs/interop/issues/71) and auto-file issues when a specific goroutine count increases by 100x (usually indicates an issues). Note: this'll have a bunch of false positives but it's a good signal.
    * [ ] Same with the heap: File an issue if the "top memory user in a steady state" changes.
    * [ ] Same with the CPU profile.
  * Network Simulation
    * Libp2p Test Lab: Realistic test networks.
      * [ ] DHT Tests
        * [ ] FindPeer
        * [ ] Provide/FindProviders
        * [ ] IPNS
      * [ ] End-to-end Bitswap (including finding providers, multiple providers, etc.).

**Comment by Stebalien** [comment]
cc @ipfs/wg-infrastructure

**Comment by lanzafame** [comment]
As part of the end-to-end benchmarking, can we look at some tooling around the storage of the benchmarks, over just comparing on a PR by PR basis, i.e. https://github.com/golang/perf or https://github.com/influxdata/grade

**Comment by Stebalien** [comment]
@lanzafame I've added a item to the todo list.

**Comment by lanzafame** [comment]
@Stebalien I have updated the issue with the point about RC telemetry.

**Comment by yiannisbot** [comment]
On the issue of Network Simulation for libp2p TestLab, I've come across this: https://chepeftw.github.io/NS3DockerEmulator/ - which is a docker emulator that can then be imported in NS-3 (https://nsnam.org). The production IPFS/libp2p/DHT code is packaged in a docker container, which represents a node in the network. Through NS-3 we then do the network setup and run the simulation (it's more emulation than simulation TBH). This can produce realistic results using production code. It might not be useful for all purposes, but surely it can be for many cases.

**Comment by jbenet** [comment]
Links
- https://github.com/ipfs/notes/issues/202
- https://github.com/ipfs/notes/issues/211
- https://github.com/ipfs/test-lab/issues/10#issuecomment-285080717

**Comment by Jorropo** [comment]
I don't think `Dial Latency (testing the dialer, transports, etc.).` is not an IPFS part, I think this test is libp2p releated because its impossible to fix any problem about that in IPFS without changing the libp2p codebase, also that test and his result impact all libp2p users, such as filecoin, IPFS, ethereum 2.0...

**Comment by Stebalien** [comment]
@Jorropo these are tests needed _by_ go-ipfs, not necessarily tests _of_ go-ipfs. That is, we want to test these libp2p features before we cut a release.
