### ISSUE TITLE
Improve Add Performance W/ Async Datastores

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-ipfs#6775]
fixes https://github.com/ipfs/go-ipfs/issues/6523

* [x] Add async write support to datastores - https://github.com/ipfs/go-datastore/issues/137
* [x] Add `Sync` calls where appropriate (e.g., when pinning).
* [x] Turn syncwrites off on badger in go-ipfs by default.
* [ ] Switch to badger by default - https://github.com/ipfs/go-ipfs/issues/4279.

**Comment by aschmahmann** [comment]
## Proposal for where to add Sync calls in go-ipfs (and related libraries)

The overall plan is to determine the places where a user would expect data to be persisted to disk and make sure we've called sync then such that a crash.

If the data that needs to be persisted is IPLD blocks then we should sync the entire blockstore, and if the data could be in the filestore then we should sync the entire filestore as well.

- Pinning: Any modification of the pin set
  - Call Sync during a Pin Flush on (in order):
      - The blockstore because of potentially new DAG nodes added during a sync
      - The blockstore because of potential changes to the DAG storing the pinset
    - The datastore key that points to the root of the pin set
- Adding data to IPFS: After an add operation is completed the data should be synced
   - Data can potentially be added to either the filestore or blockstore
   - Call Sync on the blockstore + filestore after an add completes
- MFS: Anytime the root is modified
   - Data can potentially be added to either the filestore or blockstore (confirm?)
   - Call Sync during an MFS Flush on (in order):
      - The blockstore + filestore because of potentially new DAG nodes added during a sync
     - The datastore key that points to the MFS root
- IPNS: When an update is submitted (before any network calls are made)
     - Sync an IPNS key whenever it is created and added to the datastore

**Comment by Stebalien** [comment]
So, the goal was to improve add performance on hard disks. However, testing this on my SSD, I'm still seeing a 2x speedup. That is, 145MB/s versus 73MB/s.

:clap::clap::clap:

**Comment by momack2** [comment]
Do we still plan to switch to badger by default, or is this item considered closed (at least, as far as the 0.5 release is concerned in https://github.com/ipfs/go-ipfs/issues/6776?

**Comment by Stebalien** [comment]
@momack2 I've updated the meta issue. You're right, this is "closed" as far as 0.5.0 is concerned.

**Comment by Stebalien** [comment]
This issue isn't really helping anything so I'm closing it. We still want to switch to a different datastore, but, well, details in the badger issue.
