### ISSUE TITLE
Path to landing Bitswap PoC

### ISSUE THREAD

**Issue by dirkmc** [ipfs/go-ipfs#6782]
We're currently working on a [proof-of-concept for Bitswap](https://github.com/ipfs/go-bitswap/pull/189) to improve performance by disseminating information about how blocks are distributed amongst peers. This issue outlines the remaining steps required to complete it:
- [x] Complete PoC code review
- [ ] Close out remaining issues:
  - [x] [Timeout Management](https://github.com/ipfs/go-bitswap/issues/244)
  - [x] [Debounce wants](https://github.com/ipfs/go-bitswap/issues/245)
  - [x] [Prune peers from Session if they stop sending blocks](https://github.com/ipfs/go-bitswap/issues/257)
  - [x] [Session should broadcast when all peers are removed](https://github.com/ipfs/go-bitswap/issues/259)
  - [x] [Simulate DONT_HAVE when peer doesn't respond to want-block (new peers)](https://github.com/ipfs/go-bitswap/pull/284)
  - [ ] [Docs + Code cleanup](https://github.com/ipfs/go-bitswap/issues/246)
- [x] Create proposal for testground test suite
- [x] Implement testground test suite
  - [x] Measure Performance (compare with master) https://github.com/ipfs/testground/pull/345
  - [x] Version compatibility https://github.com/ipfs/testground/issues/435
  - [x] Fuzz Test Plan https://github.com/ipfs/testground/issues/427
  - [x] Seed Selection https://github.com/ipfs/testground/issues/436

After landing PoC:
- [ ] implement server side of PoC in Javascript (HAVE / DONT_HAVE messages)
  https://github.com/ipfs/js-ipfs-bitswap/pull/211
- [ ] tackle rate limiting

**Comment by dirkmc** [comment]
### Perfomance comparison of master vs proof-of-concept

We collected performance data of bitswap against the [proof-of-concept](https://github.com/ipfs/go-bitswap/pull/189) branch of Bitswap using a [testground test suite](https://github.com/ipfs/testground/pull/345).

In particular we are interested in comparing
- time to fetch at different latency / bandwidth, for varying numbers of leeches and seeds
- number of duplicate blocks fetched

#### 5ms latency, variable bandwidth: 1 seed, 2 seeds, 4 seeds

<img width="300" alt="5ms-1024MB" src="https://user-images.githubusercontent.com/169124/73398685-ef531480-42b3-11ea-8054-d572abf7eea1.png"><img width="300" alt="5ms-160MB" src="https://user-images.githubusercontent.com/169124/73398686-ef531480-42b3-11ea-9b43-d978dc9c8e5d.png"><img width="300" alt="5ms-40MB" src="https://user-images.githubusercontent.com/169124/73398687-ef531480-42b3-11ea-930f-d63afee8e465.png"><img width="300" alt="5ms-20MB" src="https://user-images.githubusercontent.com/169124/73398688-efebab00-42b3-11ea-93c4-27509ec95315.png"><img width="300" alt="5ms-10MB" src="https://user-images.githubusercontent.com/169124/73398689-efebab00-42b3-11ea-8c11-4fe977eaf96b.png">

These graphs are for 1 leech fetching from 1, 2 and 4 seeds with 5ms latency and 10MB, 20MB, 40MB, 160MB and 1024MB bandwidth.

For high bandwidth:
- the PoC gets better performance with more seeds whereas master gets *worse* performance with more seeds
- the PoC performs much better than master

For low bandwidth:
- the PoC and master both get better performance with more seeds
- the PoC performs somewhat better than master

#### 5ms latency, variable bandwidth: 3 leeches fetching from 3 seeds

<img width="300" alt="3x3-5ms-1024MB" src="https://user-images.githubusercontent.com/169124/73399214-dbf47900-42b4-11ea-9a82-c4f7effb21ae.png"><img width="300" alt="3x3-5ms-160MB" src="https://user-images.githubusercontent.com/169124/73399215-dbf47900-42b4-11ea-98b6-70cc1c0df51a.png"><img width="300" alt="3x3-5ms-40MB" src="https://user-images.githubusercontent.com/169124/73399216-dbf47900-42b4-11ea-91b4-61953e7113f1.png"><img width="300" alt="3x3-5ms-10MB" src="https://user-images.githubusercontent.com/169124/73399218-dbf47900-42b4-11ea-9116-81a81582801c.png">

These graphs are for 3 leeches downloading simultaneously from 3 seeds. It seems like at any bandwidth the results are similar:
- PoC is faster, particularly for higher bandwidth / file size
- PoC results seem to be more consistent (points are less scattered)

#### Duplicate blocks - 5ms latency, variable bandwidth: 1 seed, 2 seeds, 4 seeds

<img width="300" alt="dups-5ms-1024MB" src="https://user-images.githubusercontent.com/169124/73399380-1fe77e00-42b5-11ea-8281-424d6015976e.png"><img width="300" alt="dups-5ms-160MB" src="https://user-images.githubusercontent.com/169124/73399381-1fe77e00-42b5-11ea-8808-eb08bc81479c.png"><img width="300" alt="dups-5ms-40MB" src="https://user-images.githubusercontent.com/169124/73399382-1fe77e00-42b5-11ea-9b59-c5eecf36409d.png"><img width="300" alt="dups-5ms-20MB" src="https://user-images.githubusercontent.com/169124/73399383-1fe77e00-42b5-11ea-975d-7ec23031b9e8.png"><img width="300" alt="dups-5ms-10MB" src="https://user-images.githubusercontent.com/169124/73399384-1fe77e00-42b5-11ea-9f07-785da87b02cb.png">

These graphs show the number of duplicate blocks received by the leech for 1, 2 and 4 seeds.
Note that in the case of 1 leech / 1 seed, there will be no duplicates.
The points are highly scattered, but the results are generally as expected:
- For the PoC there are rarely any duplicates, at any bandwidth
- For master there are more duplicates when there are more seeds, and at lower bandwidths

#### 100ms latency / variable bandwidth: 1 seed, 2 seeds, 4 seeds

<img width="300" alt="100ms-1024MB" src="https://user-images.githubusercontent.com/169124/73398419-75229000-42b3-11ea-8bbd-ea0a396ca421.png"><img width="300" alt="100ms-160MB" src="https://user-images.githubusercontent.com/169124/73398420-75229000-42b3-11ea-9dfa-40477244f227.png"><img width="300" alt="100ms-40MB" src="https://user-images.githubusercontent.com/169124/73398421-75229000-42b3-11ea-90a6-5d7cb326eaac.png"><img width="300" alt="100ms-20MB" src="https://user-images.githubusercontent.com/169124/73398423-75229000-42b3-11ea-93e4-76597d7fbc62.png"><img width="300" alt="100ms-10MB" src="https://user-images.githubusercontent.com/169124/73398425-75229000-42b3-11ea-8b7c-7ccfacce6146.png">

These results for variable bandwidths with 100ms latency are similar to those with 5ms latency above.

**Comment by momack2** [comment]
OMG SHIP IT! (@hinshun - some pretty graphs to show off validating all the great work)

**Comment by jbenet** [comment]
Fantastic perf improvements! Great graphs! 🎉🎆❤️🚀

**Comment by bertrandfalguiere** [comment]
Holy ship! 🚀

**Comment by dirkmc** [comment]
Shout out to @Stebalien with whom we came up with the design ideas, and who reviewed the [9,000 line PR](https://github.com/ipfs/go-bitswap/pull/189), @hinshun who created the test environment to validate the initial proof-of-concept and to the testground team ❤️

**Comment by obo20** [comment]
This is amazing. Great work all around. We're super excited to see this make it to production.

**Comment by whyrusleeping** [comment]
Fantastic! This is great stuff @dirkmc :)

**Comment by dirkmc** [comment]
🎉
