### ISSUE TITLE
Fixing Bootstrapping

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-ipfs#6797]
#### Version information:

> v0.5.0-dev

#### Description:

Libp2p recently increased the minimum RSA key size to 2048 bits. While almost all nodes in the network are using 2048 bit keys already, most of the built-in bootstrap nodes _are not_.

Luckily, we did have some newer nodes using 2048 bit keys. Specifically, the /dnsaddr/bootstrap.libp2p.io nodes. Unfortunately:

1. These bootstrappers were added (relatively) recently. Nodes with older configs won't use them.
2. The DNS record for these bootstrappers was _too large_: 4 bootstrappers, 4 IP addresses per bootstrapper) to fit into a single UDP packet.

To solve 2, we switched to indirect dnsaddr records: now we have 4 top-level records that each resolve two two dnsaddr records, one for each IP address for each bootstrapper. _These_ records all, individually, fit into single UDP packets.

Unfortunately, go-libp2p doesn't support recursive dnsaddr resolution: https://github.com/libp2p/go-libp2p/issues/744.

---

So, we need to:

* [x] Add support for recursive dnsaddr resolution to go-libp2p (https://github.com/libp2p/go-libp2p/issues/744).
* [x] Add a repo migration that:
    * Checks if we already have the new bootstrappers in the config. If so, skip.
    * Checks to see if we have bootstrappers with known sub 2048 bit keys. If not, skip.
    * Otherwise, remove them and replace these old bootstrappers with the new bootstrappers.
    * Replace the `/ipfs` part of these multiaddrs with `/p2p` (no reason not to).
* [x] Test the migration.
* [x] Update the repo version in go-ipfs.

**Comment by dirkmc** [comment]
Which of [the peers](https://github.com/ipfs/go-ipfs-config/blob/master/bootstrap_peers.go#L21) have sub 2048 bit keys?

**Comment by olizilla** [comment]
The ones addressed by `/dnsaddr`... https://github.com/ipfs/go-ipfs-config/blob/98ec0ae9a3161d355da0615e54ca314232212615/bootstrap_peers.go#L22-L25

**Comment by Stebalien** [comment]
@olizilla & @dirkmc 

Ok, so, the nodes with peer IDs that start with QmSoL are the ones we need to remove. Notably, mars (/ip4/104.131.131.82/tcp/4001/p2p/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ), uses a 4096 bit key. Let's leave that one where it is.

**Comment by Stebalien** [comment]
@olizilla so, something has come up: when we update our _new_ bootstrappers to the next go-ipfs release, we need to use a custom build that can (a) connect to the _old_ bootstrappers and (b) does not disconnect from the old bootstrappers. Otherwise, peers connecting to the old bootstrappers will be isolated from the rest of the network.

**Comment by olizilla** [comment]
Exciting! That's ok, we can roll out a custom build from a branch of go-ipfs like we do for gateways.

@Stebalien let me know the branch you set up for that, and I'll set up an autobuild rule for it on dockerhub.

**Comment by Stebalien** [comment]
:+1:
