### ISSUE TITLE
Reliable, performant logging

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-ipfs#7065]
We've recently switched from a custom logging backend to zap as our logging backend. The upside is structured logging but there are quite a few downsides:

* [ ] We need to re-implement the "mirror" logging logic. That is, we need to be able to add/remove additional sinks (e.g., a `ipfs log tail` sink) at runtime.
* [ ] The default file backend is unbuffered. This has terrible performance.
* [ ] The new backend _blocks_ if we log too much. We should log till we fill up a reasonable buffer, then start dropping messages.
* [ ] We've currently implemented multiple logging subsystems through multiple independent loggers. Instead, we should have a _single_ zap core.

**Comment by hsanjuan** [comment]
I wonder if we should look into https://godoc.org/github.com/hashicorp/go-hclog ?

**Comment by Stebalien** [comment]
I'm not sure how that'll help. We switched to Zap because we wanted structured logging. I'm not suggesting we switch away from it, I'm saying that we need to write some better backends/tooling around it.

**Comment by hsanjuan** [comment]
hclog supports structured logging (if that is json output https://godoc.org/github.com/hashicorp/go-hclog#LoggerOptions), and I'm assuming it will be solid. Implementing buffering on top of a logger sounds like doing half of the job of what a logger should do.

> The default file backend is unbuffered. This has terrible performance.

Funny enough, they claim to be super performant on their repo...

**Comment by Stebalien** [comment]
> Implementing buffering on top of a logger sounds like doing half of the job of what a logger should do.

Zap supports different backends. My plan would be to implement logging _under_ the zap, not over it, with a custom backend.

At this point, I _really_ don't want to switch to a new logging system unless we absolutely have to.

Note: By structured logging, I mean the ability to attach arbitrary structured data to log messages. In zap, I can write `logger.Infow("message", "error", error, "from", pid)`.

> Funny enough, they claim to be super performant on their repo...

I assume they're expecting users with performance constraints to use a different/custom backend instead of writing to a file.

**Comment by Stebalien** [comment]
Turns out zap does support sampling. That is, you can tell it to log N messages with the same "message" every N seconds, then only log every Mth message with that "message". Given that the message is usually a fixed string while all the data is in the structured args, this should work well in practice.

Except in our peer logging plugin...
