### ISSUE TITLE
Tracking: Improving ErrNotFound

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/go-ipfs#7074]
@Stebalien this is meant to hold a small async discussion about continuing ErrNotFound approach, for lack of a better place (would affect multiple repos).

We have done: https://github.com/ipfs/go-ipld-format/pull/55

And now, roughly:

go-datastore has an ErrNotFound.

go-ipfs-blockstore sees those and turns them into it's own ErrNotFounds

go-blockservice sees those and turns them into it's own ErrNotFounds

go-merkledag sees those and turns them into the ipld.ErrNotFound that we fixed.

Two possible approaches:

* A: Remove package-specific ErrNotFound for blockstore, blockservice and merkledag and use and bubble ipld.ErrNotFound{CID} from the blockstore. This reduces lines of code. At the top level (go-ipfs), check with errors.Is(error, ipld.ErrNotFound{}), where needed.

* B: 
  * Modify all ErrNotFound types in blockstore, blockservice, merkledag (and potentially datastore), to be able to include CID information and NotFound() method
  * Bubble errors directly without re-converting them on every module.
  * At the top-level, where it matters to verify something is a NotFound, check with `errors.As()` to see if what we got implements the NotFound() interface.
  * This is more righteous at the expense of some more, duplicated code.

For practical reasons, I lean towards A, given that Blockstore, blockservice, merkledag, ipld-format are almost like internal modules in the go-ipfs codebase, and then it would not be too crazy to consolidate on a single error type for this.

(of  course I can bypass all this and just make go-merkledag work with the new ipld.ErrNotFound, but I thought I'd ask as this would all be quick to fix in one go, either way).

Thoughts?

**Comment by bonedaddy** [comment]
A sounds like best approach. I was updating some dependencies and found that the IPLD format update broke merkledag so I tried implementing the patch in a fork to push upstream and it's not as intuitive as before when it comes to handling the error.

For example https://github.com/RTradeLtd/go-merkledag/blob/fix%2Fipldformat/dagutils/utils.go#L100 this doesn't take a cid.Cid type so you have to do cid.Decode to get the CID to use in error checking, but the decode process also returns an error. 

Bubbling this up, and not needing to do cid type conversion in top level could would be extremely helpful

**Comment by bonedaddy** [comment]
> you can leave the cid empty too...

Didnt know that

> As a side note, don't be overly aggressive updating dependencies (patch version bumps are fine), but other than that I'd keep go-ipfs's go.mod as reference.

Normally I dont but dependabot picked this the ipld format change in a PR and it failed so I was curious what it would take to get resolved.

**Comment by hsanjuan** [comment]
Discussed with @Stebalien , we're taking approach A. We will merge go-ipfs-block-format with go-ipld-format in the future (keeping aliases for backwards compat), for added consistency.

**Comment by hsanjuan** [comment]
Ok, I am going to hijack this issue to track this effort.

* [ ] This can only happen post 0.5.0, when we move to raw-multihashes because we have already merged/updated go-blockstore for that and I don't want to undo that just for this.
* [ ] We have reverted changes to go-ipld-format as they were breaking and blocking, so that revert needs to be reverted and tagged.
* [ ] ipfs/go-ipfs-blockstore#48 needs to be merged to start using ipld.ErrNotFound{cid} + tag.
* [ ] ipfs/go-bitswap#339 needs merging to use the new blockstore + tag
* [ ] ipfs/go-blockservice#55 needs merging with the new blockstore and bitswap + tag
* [ ] ipfs/go-ipfs-exchange-offline#27 needs merging to improve the offline error message with the new ipld error + tag
* [ ] ipfs/go-merkledag#54 needs merging with the new blockservice, offline exchange, blockstore + tag
* [ ] https://github.com/ipfs/go-filestore/pull/31 needs merging with the new merkledag and ipld errors
* [ ] go-ipfs needs to bump all those dependencies and adapt to the new ipld.ErrNotFound

**Comment by hsanjuan** [comment]
@Stebalien I request inclusion in 0.6.0 milestone.

**Comment by hsanjuan** [comment]
Behold, for we have finally moved away from raw multihashes and this has been unblocked!

**Comment by Stebalien** [comment]
:turtle: :checkered_flag:

**Comment by BigLep** [comment]
@hsanjuan @Jorropo : I assume we're going to need to do a bunch of releases on so this can bubble up to go-ipfs.

I suggest we use the versioning suggestions/tooling here: https://github.com/protocol/.github/blob/master/VERSIONING.md

If help is needed with the versioning workflow, please discuss in IPFS Discord / #ip-productivity.

**Comment by hsanjuan** [comment]
A small follow up for the tagging was on #8757 . This is now finally closed.
