### ISSUE TITLE
Filestore Experiment

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-ipfs#7161]
This is a tracking issue for the unstable filestore feature.

* [ ] Remove the path restrictions (https://github.com/ipfs/go-ipfs/issues/4224). This may require additional work and/or security hardening.
* [ ] Track down a potential data loss and/or deadlock bug: https://github.com/ipfs/go-ipfs/issues/5815
* [ ] GC should work even if files backing other files in the filestore disappear: https://github.com/ipfs/go-ipfs/issues/7160.

We should also look into fixing https://github.com/ipfs/go-ipfs/issues/5987, but that's not a requirement to stabilize.
