### ISSUE TITLE
[META] IPNS/Namesys Todo

### ISSUE THREAD

**Issue by aschmahmann** [ipfs/go-ipfs#7572]
You may have noticed that IPNS, while very handy, has a number of ongoing issues. Let's use this issue to track them. Before adding in new bugs I'd recommend reading through the existing list.

We'll likely need an overhaul of the IPNS/Namesys APIs

- [ ] IPNS over PubSub still requires the DHT for resolving non-self/identity keys #6360 
- [ ] IPNS TTL/caching Issues #7564 
     - [ ] IPNS over PubSub caches the latest record for each key indefinitely
- [ ] IPNS Republisher ignores EOL #7537
- [ ] `ipfs name resolve --nocache` does nothing
- [ ] Resolved IPNS/Namesys records are not cached/stored in the datastore (i.e. does not work when restarting in offline mode)
- [ ] IPNS pinning (e.g. #4435)
     - [ ] Pin IPNS keys so that we search for the latest records upon restart
     - [ ] Recursively pin/unpin the data pointed to by an IPNS pin
- [ ] IPNS records should be republishable by third parties without requiring them to have the private key #3117
- [ ] Come up with a better way of describing the distinction between Namesys, DNSLink, IPNS and `ipns://`
