### ISSUE TITLE
[Meta: GH issue templates] Stale checklist that can be converted into issues by just one click

### ISSUE THREAD

**Issue by schomatis** [ipfs/go-ipfs#8313]
### Checklist

- [X] This is a bug report, not a question. Ask questions on [discuss.ipfs.io](https://discuss.ipfs.io).
- [X] I have searched on the [issue tracker](https://github.com/ipfs/go-ipfs/issues?q=is%3Aissue) for my bug.
- [X] I am running the latest [go-ipfs version](https://dist.ipfs.io/#go-ipfs) or have an issue updating.

### Installation method

ipfs-desktop

### Version

```Text
..
```

### Config

```json
..
```

### Description

The [Enhancement](https://github.com/ipfs/go-ipfs/issues/new?assignees=&labels=kind%2Fenhancement&template=enhancement.yml) template (and probably others) leave a stale checklist in its body (a requirement to submit the issue in the first place but _not_ actual content to remain there afterward) that clutters the issue and also exposes some weird UX behavior that can turn one of its items into a new issue by just one click (see https://github.com/ipfs/go-ipfs/issues/8312 as an example).

**Comment by Stebalien** [comment]
There have been requests for checklists that _don't_ get submitted along with the issue, but nothing has been implemented. Unfortunately, the previous list (without checkboxes) wasn't effective.

> also exposes some weird UX behavior that can turn one of its items into a new issue by just one click (see #8312 as an example).

I'm not sure _how_ you triggered that, but that sounds like a bug.

---

Do you have any suggested fixes/improvements?

**Comment by Stebalien** [comment]
Ah: https://github.com/github/feedback/discussions/4261

**Comment by Stebalien** [comment]
Also https://github.com/github/feedback/discussions/4577
