### ISSUE TITLE
Update GitHub workflows to use central ipfs install/start Action

### ISSUE THREAD

**Issue by BigLep** [ipfs/go-ipfs#8511]
**Done criteria:** remove duplication of common steps in our GitHub workflows (e.g., install IPFS, start it, wait for daemon to be running)
**Why important:** general duplication reduction and make future work quicker.
**Customer:** dev team
**Notes:** 
* An example where this was discussed: https://github.com/ipfs/go-ipfs/pull/8494#discussion_r728494937
**TODO**
- [x] https://github.com/ipfs-shipyard/git-remote-ipld/pull/39
- [x] https://github.com/ipfs/go-ds-s3/pull/212
- [x] https://github.com/ipfs/go-ipfs-api/pull/262
- [x] https://github.com/ipfs/go-ipfs-http-client/blob/c832fc0ce1d8235c830fecd0dd44dda04a9fba37/.github/actions/go-test-setup/action.yml (nothing to do here)
- [x] https://github.com/ipfs/go-ipfs/pull/8609
- [x] https://github.com/ipfs/distributions/pull/520 (?)
- [x] https://github.com/libp2p/go-libp2p-relay-daemon/pull/13
