### ISSUE TITLE
  Enable IPNS over pubsub by default 

### ISSUE THREAD

**Issue by lidel** [ipfs/go-ipfs#8591]
### Checklist

- [X] My issue is specific & actionable.
- [X] I am not suggesting a protocol enhancement.
- [X] I have searched on the [issue tracker](https://github.com/ipfs/go-ipfs/issues?q=is%3Aissue) for my issue.

### Description

> This depends on https://github.com/ipfs/go-ipfs/issues/6621 but adds items on top of it.

Ref. https://github.com/ipfs/go-ipfs/blob/master/docs/experimental-features.md#ipns-pubsub

## TODO placeholder

- [ ] figure out GC for unused topics 
  - an idea: https://github.com/ipfs/go-ipfs/issues/8586 IPNS Pubsub Reprovider Duration (GC for unused topics)
- [ ] figure out if we need one topic per libp2p-key (baloons nr of subscriptions on public  HTTP gateways)
- [ ] decide if we tweak the topic name convention to something more compact
