### ISSUE TITLE
Meta: HTTP Gateway cache control improvements

### ISSUE THREAD

**Issue by lidel** [ipfs/go-ipfs#8717]
This is a meta issue for HTTP cache improvements that we should prioritize in go-ipfs:
- [ ] `max-age` on `/ipns/` based on TTL – https://github.com/ipfs/go-ipfs/issues/1818
- [ ] dir-index-html on `/ipfs/` should have some reasonable `max-age` (it won't change within releases)
  -  (wip: `fix/dir-index-html-max-age` @lidel)
- [ ] some HTTP header in `/ipns/` responses which contains resolved IPNS (root CID)  for faster cache invalidation of entire website when IPNS pointer changes
   - suggested in https://github.com/ipfs/go-ipfs/pull/8617
      - proposed `X-Ipfs-Roots` in https://github.com/ipfs/go-ipfs/pull/8720 a way to indicate all CIDs required for resolving  path segments  from `x-ipfs-path`
-  [ ] ensure we default to https://web.dev/stale-while-revalidate/ everywhere we can
  - this maximizes utility of HTTP gateway – cache-control is used not only by end user (browsers), but also HTTP  caching solutions, CDNs. We should have defaults that leverage HTTP caching tools and conversions, assuming people will manually configure HTTP caching on their own using some sane values is not realistic.

cc @thattommyhall & @mathew-cf) if there are more asks/ideas here

**Comment by thattommyhall** [comment]
Only thing I would add is a strategy of expiring at "top of the hour" or "end of the day" for the DirIndex pages makes dealing with when the etag does eventually change a bit nicer (you wont see different things on different servers for as long), which nudges me to prefer Expires to Cache-Control (but its not _that_ much extra to calculate it anyway)

**Comment by mathew-cf** [comment]
An idea in addition to the ones proposed:
A public resolution endpoint for gateways could be useful as an inexpensive, cacheable call. There is no way to do IPNS public key resolution without directly accessing the IPFS network or fetching the whole file, so an endpoint exposing the resolution could be helpful for that.

**Comment by thattommyhall** [comment]
@mathew-cf thats useful, but you'd have to rewrite to fetch /ipfs/<cid>/<path> or you couldnt be certain that the content you fetched matched. Like if I checked what the dnslink was for blog.ipfs.io then fetched /ipns/blog.ipfs.io it might have changed in the meantime

**Comment by mathew-cf** [comment]
By cacheable, I meant for a short TTL (~1 min). This resolution response can still be supplemented by DNS resolution for faster cache verification/invalidation. If you have the x-ipfs-roots header, you can check that the resolution and response match and choose whether to cache the response.

I'm thinking in the context of using CF workers here if that helps clarify the context.

**Comment by mathew-cf** [comment]
@lidel That works for me!

**Comment by thattommyhall** [comment]
I tested something like your dir-index-html strategy with lua nginx, but I used `X-Accel-Expires` to keep it within our gateway. 
Nginx will honor it, I think maybe Varnish but I cant find a clear ref (though I would be near-certain there is an equivalent)

So configuring the name of the header might be useful is the concrete ask here, but someone else that uses another cache might be able to chime in

**Comment by lidel** [comment]
If we fix https://github.com/ipfs/go-ipfs/issues/1818#issuecomment-1015849462 (set proper `cache-control` header of `/ipns/` and dir-index-html responses),  that would be universal hint for all HTTP caching tools/solutions (in case where gateway operator wants to cache things for longer, the minimal max-age could be raised via config, decreasing the need for custom headers like `X-Accel-Expires`)

**Comment by thattommyhall** [comment]
@lidel did fix/dir-index-html-max-age land somewhere?

**Comment by lidel** [comment]
@thattommyhall  kinda: https://github.com/ipfs/go-ipfs/pull/8758  fixed a bug and now adds  `cache-control` when a directory has `index.html` and returns it instead of dir listing response. 

Generated dir listings don't have  `cache-control` header, but they have deterministic `Etag`  + will return HTTP 304 Not Modified if client sends matching Etag in `If-None-Match` header.

**Comment by thattommyhall** [comment]
I'd like to advocate for something like top of the hour Expires or something there too

**Comment by lidel** [comment]
@thattommyhall  I am leaning towards setting `Cache-Control` that asks for caching forever (`immutable`), because dir listing is costly to generate, and we don't change them that often.

Given how people deploy gateway infra, we would still want to revalidate on CDN/caching proxies, so how about:

```
Cache-Control: public, max-age=31536000,  stale-while-revalidate=86400, stale-if-error=86400, immutable
```

My understanding is the caching proxy will always return a cached version of dir listing, but will try to revalidate if the cached copy is older than a week. 

Thoughts?

**Comment by lidel** [comment]
Closing: everything on this checklist has shipped: `X-Ipfs-Roots` in v0.13 (#8720), TTL-based `max-age` on `/ipns/` in v0.24, and `stale-while-revalidate` on generated directory listings in v0.30 (ipfs/boxo#643), joining the immutable `max-age` on `/ipfs/` we had since 0.4.x. All true since v0.30, with further refinements in v0.43 (DNSLink TTLs, IPNS EOL capping, 304 revalidation headers).
