### ISSUE TITLE
F2F low-diffusion filesharing app

### ISSUE THREAD

**Issue by MichaelMure** [ipfs/go-ipfs#961]
This is a meta-bug that reference bugs that needs to be resolved for the following project. If it's not the good place for that, feel free to close it.

I would really like to see happen a friend-to-friend filesharing app with the following caracteristics:
- targeted for private/low diffusion data between people that know each-others. Main use case: friends want to share between each-others their holidays pictures.
- low friction: it should be as easy as possible
- encryption should be used to maintain privacy and control the diffusion of the data

The underlying goal is to reduce the need to use solution like Facebook, Dropbox, Drive... for file/pictures exchange that should be kept private. Also [this](https://xkcd.com/949/).

IPFS seems to be the perfect backend for this project. What I envision is a thin GUI layer that provide the low-friction caracteristics. Most of the actual feature would be in IPFS. Here is the issues that needs to be resolved for this project to happen:
- [ ] jbenet/go-ipfs/issues/875 : avoid duplicating files added to ipfs, ie having ipfs track and share files that are directly on disk, not copied in the datastore
- [ ] jbenet/go-ipfs/issues/930 : API access to current download 
- [ ] ipfs/specs/issues/3 : keystore, encryption, signing and key sharing support
- [ ] jbenet/ipfs/issues/45 : having a node keypair and an identity keypair
- [ ] pub/sub system : @cryptix mentionned this system as a way for user to notify the receiver that somethng was shared to them, need more details

Optional:
- [ ] jbenet/go-ipfs/issues/920 Need statistics on what content is being uploaded
- [ ] jbenet/go-ipfs/issues/826 Private keys should be encrypted

On a side note, a problem that arise with low-diffusion filesharing is that sender and receivers need to be online at the same time. The future Filecoin seems to be a good solution to mitigate this problem as the sender could incentive other nodes to replicate and hold the encrypted blob online while he is offline.

**Comment by jbenet** [comment]
> This is a meta-bug that reference bugs that needs to be resolved for the following project. If it's not the good place for that, feel free to close it.

This may be a better issue for https://github.com/ipfs/spec -- actually, maybe worth doing it in a https://github.com/ipfs/faq repo.

> The underlying goal is to reduce the need to use solution like Facebook, Dropbox, Drive... for file/pictures exchange that should be kept private. Also this.
> 
> IPFS seems to be the perfect backend for this project.

Yeah, IPFS is designed to solve this use case. (and others).

---

The issues you track here are good. i imagine more things being needed to work really well. can already start on this. I should mention that we're interested in making this too, so probably should just work together.

> On a side note, a problem that arise with low-diffusion filesharing is that sender and receivers need to be online at the same time. The future Filecoin seems to be a good solution to mitigate this problem as the sender could incentive other nodes to replicate and hold the encrypted blob online while he is offline.

Yep, precisely!

**Comment by Konubinix** [comment]
I am very interested in such a feature. I have exacly the same requirements as @MichaelMure.

In my mind, the most critical point to reach the "low friction" aspect is #875.

**Comment by MichaelMure** [comment]
Closing this issue as it's better suited elsewhere.
